config/routes.rb
Rails.application.routes.draw do
  resources :meals
  resources :foodies
end

app/models/foodie.rb
class Foodie < ApplicationRecord

  belongs_to :meal

  def self.order_by_name
    order(:name)
  end

  validates :name, presence: true
  validates :content, presence: true


end

app/models/meal.rb
class Meal < ApplicationRecord
<<<<<<< HEAD
  has_many :foodies
||||||| merged common ancestors
=======
  validations :name, presence: true
  validations :image_url, length: { maximum: 250 }, allow_blank: true
>>>>>>> 1016ca86619b2e7eeec2cf2519e5f9765ae90e6f
end

app/controllers/foodies_controller.rb
class FoodiesController < ApplicationController
  before_action :set_foody, only: [:show, :edit, :update, :destroy]

  # GET /foodies
  # GET /foodies.json
  def index
    @foodies = Foodie.all
  end

  # GET /foodies/1
  # GET /foodies/1.json
  def show
  end

  # GET /foodies/new
  def new
    @foody = Foodie.new
  end

  # GET /foodies/1/edit
  def edit
  end

  # POST /foodies
  # POST /foodies.json
  def create
    @foody = Foodie.new(foody_params)

    respond_to do |format|
      if @foody.save
        format.html { redirect_to @foody, notice: 'Foodie was successfully created.' }
        format.json { render :show, status: :created, location: @foody }
      else
        format.html { render :new }
        format.json { render json: @foody.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /foodies/1
  # PATCH/PUT /foodies/1.json
  def update
    respond_to do |format|
      if @foody.update(foody_params)
        format.html { redirect_to @foody, notice: 'Foodie was successfully updated.' }
        format.json { render :show, status: :ok, location: @foody }
      else
        format.html { render :edit }
        format.json { render json: @foody.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /foodies/1
  # DELETE /foodies/1.json
  def destroy
    @foody.destroy
    respond_to do |format|
      format.html { redirect_to foodies_url, notice: 'Foodie was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_foody
      @foody = Foodie.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def foody_params
      params.require(:foodie).permit(:name, :content, :image_url)
    end
end

app/controllers/meals_controller.rb
class MealsController < ApplicationController
  before_action :set_meal, only: [:show, :edit, :update, :destroy]

  # GET /meals
  # GET /meals.json
  def index
    @meals = Meal.all
  end

  # GET /meals/1
  # GET /meals/1.json
  def show
  end

  # GET /meals/new
  def new
    @meal = Meal.new
  end

  # GET /meals/1/edit
  def edit
  end

  # POST /meals
  # POST /meals.json
  def create
    @meal = Meal.new(meal_params)

    respond_to do |format|
      if @meal.save
        format.html { redirect_to @meal, notice: 'Meal was successfully created.' }
        format.json { render :show, status: :created, location: @meal }
      else
        format.html { render :new }
        format.json { render json: @meal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /meals/1
  # PATCH/PUT /meals/1.json
  def update
    respond_to do |format|
      if @meal.update(meal_params)
        format.html { redirect_to @meal, notice: 'Meal was successfully updated.' }
        format.json { render :show, status: :ok, location: @meal }
      else
        format.html { render :edit }
        format.json { render json: @meal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /meals/1
  # DELETE /meals/1.json
  def destroy
    @meal.destroy
    respond_to do |format|
      format.html { redirect_to meals_url, notice: 'Meal was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_meal
      @meal = Meal.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def meal_params
      params.require(:meal).permit(:name, :image_url)
    end
end

app/helpers/foodies_helper.rb
module FoodiesHelper
end

app/helpers/meals_helper.rb
module MealsHelper
end

app/views/foodies/_form.html.erb
<%= form_for(foody) do |f| %>
  <% if foody.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(foody.errors.count, "error") %> prohibited this foody from being saved:</h2>

      <ul>
      <% foody.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :content %>
    <%= f.text_area :content %>
  </div>

  <div class="field">
    <%= f.label :image_url %>
    <%= f.text_field :image_url %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/foodies/edit.html.erb
<h1>Editing Foody</h1>

<%= render 'form', foody: @foody %>

<%= link_to 'Show', @foody %> |
<%= link_to 'Back', foodies_path %>

app/views/foodies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Foodies</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Content</th>
      <th>Image url</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @foodies.each do |foody| %>
      <tr>
        <td><%= foody.name %></td>
        <td><%= foody.content %></td>
        <td><%= foody.image_url %></td>
        <td><%= link_to 'Show', foody %></td>
        <td><%= link_to 'Edit', edit_foody_path(foody) %></td>
        <td><%= link_to 'Destroy', foody, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Foody', new_foody_path %>

app/views/foodies/new.html.erb
<h1>New Foody</h1>

<%= render 'form', foody: @foody %>

<%= link_to 'Back', foodies_path %>

app/views/foodies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @foody.name %>
</p>

<p>
  <strong>Content:</strong>
  <%= @foody.content %>
</p>

<p>
  <strong>Image url:</strong>
  <%= @foody.image_url %>
</p>

<%= link_to 'Edit', edit_foody_path(@foody) %> |
<%= link_to 'Back', foodies_path %>

app/views/meals/_form.html.erb
<%= form_for(meal) do |f| %>
  <% if meal.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(meal.errors.count, "error") %> prohibited this meal from being saved:</h2>

      <ul>
      <% meal.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :image_url %>
    <%= f.text_field :image_url %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/meals/edit.html.erb
<h1>Editing Meal</h1>

<%= render 'form', meal: @meal %>

<%= link_to 'Show', @meal %> |
<%= link_to 'Back', meals_path %>

app/views/meals/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Meals</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Image url</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @meals.each do |meal| %>
      <tr>
        <td><%= meal.name %></td>
        <td><%= meal.image_url %></td>
        <td><%= link_to 'Show', meal %></td>
        <td><%= link_to 'Edit', edit_meal_path(meal) %></td>
        <td><%= link_to 'Destroy', meal, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Meal', new_meal_path %>

app/views/meals/new.html.erb
<h1>New Meal</h1>

<%= render 'form', meal: @meal %>

<%= link_to 'Back', meals_path %>

app/views/meals/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @meal.name %>
</p>

<p>
  <strong>Image url:</strong>
  <%= @meal.image_url %>
</p>

<%= link_to 'Edit', edit_meal_path(@meal) %> |
<%= link_to 'Back', meals_path %>